# Step 1: Build the application using Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

# Step 2: Run the application using Tomcat
FROM tomcat:9.0-jdk17-openjdk-slim
WORKDIR /usr/local/tomcat

# Remove default Tomcat webapps to save resources
RUN rm -rf webapps/*

# Copy the generated WAR file from the build step into the Tomcat webapps directory
# Replace 'YourProjectName' with the exact name generated by your pom.xml build settings
COPY --from=build /app/target/*.war webapps/ROOT.war

# Expose port 8080 (Render expects web services to bind to a port)
EXPOSE 8080

# Run Tomcat
CMD ["catalina.sh", "run"]